- platform: generic_thermostat
  name: Thermostat Salon
  heater: switch.shelly_shsw_1_68b8e1
  #target_sensor:  sensor.mi_salon_temperature
  #target_sensor: sensor.mi_t_582d34348637
  target_sensor: sensor.temp_mqtt_salon
  min_temp: 15
  max_temp: 24
  ac_mode: false
  target_temp: 21
  cold_tolerance: 0.2
  hot_tolerance: 0.1
  min_cycle_duration:
    minutes: 10
  keep_alive:
    minutes: 3
  initial_hvac_mode: "heat"
  away_temp: 19
  precision: 0.1

- platform: dualmode_generic
  name: Thermostat Lola
  heater: input_boolean.sw_clim_heater_lola
  cooler: input_boolean.sw_clim_cooler_lola
  target_sensor: sensor.temp_mqtt_lola
  min_temp: 15
  max_temp: 24
  #ac_mode: false
  cold_tolerance: 0.3
  hot_tolerance: 0.1
  min_cycle_duration:
    minutes: 1
  keep_alive:
    minutes: 3
  initial_hvac_mode: "off"
  away_temp: 19
  precision: 0.1

- platform: dualmode_generic
  name: Thermostat Chambre
  heater: input_boolean.sw_clim_heater_chambre
  cooler: input_boolean.sw_clim_cooler_chambre
  #target_sensor:  sensor.mi_chambre_temperature
  target_sensor: sensor.temp_mqtt_chambre
  min_temp: 15
  max_temp: 24
  #ac_mode: false
  cold_tolerance: 0.3
  hot_tolerance: 0.1
  min_cycle_duration:
    minutes: 1
  keep_alive:
    minutes: 3
  initial_hvac_mode: "off"
  away_temp: 19
  precision: 0.1
  
  
- platform: dualmode_generic
  name: Thermostat Bureau
  heater: input_boolean.sw_clim_heater_bureau
  cooler: input_boolean.sw_clim_cooler_bureau
  #target_sensor: sensor.mi_bureau_temperature
  target_sensor: sensor.temp_mqtt_bureau
  min_temp: 15
  max_temp: 28
  #ac_mode: true
  reverse_cycle: true
  cold_tolerance: 0.3
  hot_tolerance: 0.1
  min_cycle_duration:
    minutes: 1
  keep_alive:
    minutes: 3
  initial_hvac_mode: "off"
  away_temp: 19
  precision: 0.1
  
- platform: climate_group
  name: 'Clim Daikin'
  entities:
    - climate.thermostat_bureau
    - climate.thermostat_lola



